name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (default: commit SHA)'
        required: false
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      ARTIFACT_REPOSITORY: ${{ secrets.ARTIFACT_REPOSITORY }}
      IMAGE: ${{ secrets.ARTIFACT_REPOSITORY }}:${{ github.event.inputs.image_tag || github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker --quiet $(echo "$ARTIFACT_REPOSITORY" | cut -d'/' -f1)

      - name: Build and push image
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --project "$PROJECT_ID" \
            --region "$REGION" \
            --image "$IMAGE" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars LOG_LEVEL=info,SCHEMA_CACHE_TTL_MS=300000 \
            --quiet
